### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Flymannx** [Eliepse/Twitch-Alert-Addon#1]
Hi,

First time i try to create a addon.

But we have same error in Chrome and don't find where i make my API Twitch informations.

Thx a lot !

**Comment by Eliepse** [comment]
Hi !

This is an old personal project. When I developed this addon it worked with a server that do the request and cache them (preventing to reach the request's rate limit). Did you do so ?

Can you tell me more about the error, may be I can help ?
